'use strict';

/**
 * Control hints for MAV_CMD_* parameters whose backing enum the registry
 * and `.d.ts` cannot recover (DESIGN.md §4, §14).
 *
 * Generated from mavlink/mavlink common.xml `<param enum=`> links (85).
 * Applied into `commands[cmd].params[i].enum` by the bundled loader.
 */

/** @type {Object<string, Object<number, string>>} */
const COMMAND_PARAM_ENUMS = {
  MAV_CMD_ACTUATOR_TEST: { 5: 'ACTUATOR_OUTPUT_FUNCTION' },
  MAV_CMD_COMPONENT_ARM_DISARM: { 1: 'MAV_BOOL' },
  MAV_CMD_CONDITION_GATE: { 2: 'MAV_BOOL' },
  MAV_CMD_CONDITION_YAW: { 4: 'MAV_BOOL' },
  MAV_CMD_CONFIGURE_ACTUATOR: { 1: 'ACTUATOR_CONFIGURATION', 5: 'ACTUATOR_OUTPUT_FUNCTION' },
  MAV_CMD_CONTROL_HIGH_LATENCY: { 1: 'MAV_BOOL' },
  MAV_CMD_DO_AUTOTUNE_ENABLE: { 1: 'MAV_BOOL', 2: 'AUTOTUNE_AXIS' },
  MAV_CMD_DO_CHANGE_ALTITUDE: { 2: 'MAV_FRAME' },
  MAV_CMD_DO_CHANGE_SPEED: { 1: 'SPEED_TYPE' },
  MAV_CMD_DO_ENGINE_CONTROL: { 1: 'MAV_BOOL', 2: 'MAV_BOOL', 4: 'ENGINE_CONTROL_OPTIONS' },
  MAV_CMD_DO_FENCE_ENABLE: { 2: 'FENCE_TYPE' },
  MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW: { 5: 'GIMBAL_MANAGER_FLAGS' },
  MAV_CMD_DO_GRIPPER: { 2: 'GRIPPER_ACTIONS' },
  MAV_CMD_DO_ILLUMINATOR_CONFIGURE: { 1: 'ILLUMINATOR_MODE' },
  MAV_CMD_DO_INVERTED_FLIGHT: { 1: 'MAV_BOOL' },
  MAV_CMD_DO_MOTOR_TEST: { 2: 'MOTOR_TEST_THROTTLE_TYPE', 6: 'MOTOR_TEST_ORDER' },
  MAV_CMD_DO_MOUNT_CONFIGURE: { 1: 'MAV_MOUNT_MODE', 2: 'MAV_BOOL', 3: 'MAV_BOOL', 4: 'MAV_BOOL' },
  MAV_CMD_DO_MOUNT_CONTROL: { 7: 'MAV_MOUNT_MODE' },
  MAV_CMD_DO_ORBIT: { 3: 'ORBIT_YAW_BEHAVIOUR' },
  MAV_CMD_DO_PARACHUTE: { 1: 'PARACHUTE_ACTION' },
  MAV_CMD_DO_PAUSE_CONTINUE: { 1: 'MAV_BOOL' },
  MAV_CMD_DO_REPOSITION: { 2: 'MAV_DO_REPOSITION_FLAGS' },
  MAV_CMD_DO_SET_CAM_TRIGG_DIST: { 3: 'MAV_BOOL' },
  MAV_CMD_DO_SET_HOME: { 1: 'MAV_BOOL' },
  MAV_CMD_DO_SET_MISSION_CURRENT: { 2: 'MAV_BOOL' },
  MAV_CMD_DO_SET_MODE: { 1: 'MAV_MODE_FLAG' },
  MAV_CMD_DO_SET_REVERSE: { 1: 'MAV_BOOL' },
  MAV_CMD_DO_SET_ROI: { 1: 'MAV_ROI' },
  MAV_CMD_DO_SET_SAFETY_SWITCH_STATE: { 1: 'SAFETY_SWITCH_STATE' },
  MAV_CMD_DO_SET_STANDARD_MODE: { 1: 'MAV_STANDARD_MODE' },
  MAV_CMD_DO_VTOL_TRANSITION: { 1: 'MAV_VTOL_STATE' },
  MAV_CMD_DO_WINCH: { 2: 'WINCH_ACTIONS' },
  MAV_CMD_GUIDED_CHANGE_HEADING: { 1: 'HEADING_TYPE' },
  MAV_CMD_GUIDED_CHANGE_SPEED: { 1: 'SPEED_TYPE' },
  MAV_CMD_ILLUMINATOR_ON_OFF: { 1: 'MAV_BOOL' },
  MAV_CMD_INJECT_FAILURE: { 1: 'FAILURE_UNIT', 2: 'FAILURE_TYPE' },
  MAV_CMD_NAV_GUIDED_ENABLE: { 1: 'MAV_BOOL' },
  MAV_CMD_NAV_LAND: { 2: 'PRECISION_LAND_MODE' },
  MAV_CMD_NAV_LOITER_TIME: { 2: 'MAV_BOOL' },
  MAV_CMD_NAV_LOITER_TO_ALT: { 1: 'MAV_BOOL' },
  MAV_CMD_NAV_LOITER_TURNS: { 2: 'MAV_BOOL' },
  MAV_CMD_NAV_ROI: { 1: 'MAV_ROI' },
  MAV_CMD_NAV_SET_YAW_SPEED: { 3: 'MAV_BOOL' },
  MAV_CMD_NAV_TAKEOFF: { 3: 'NAV_TAKEOFF_FLAGS' },
  MAV_CMD_NAV_VTOL_LAND: { 1: 'NAV_VTOL_LAND_OPTIONS' },
  MAV_CMD_NAV_VTOL_TAKEOFF: { 2: 'VTOL_TRANSITION_HEADING' },
  MAV_CMD_OVERRIDE_GOTO: { 1: 'MAV_GOTO', 2: 'MAV_GOTO', 3: 'MAV_FRAME' },
  MAV_CMD_PREFLIGHT_CALIBRATION: { 2: 'PREFLIGHT_CALIBRATION_MAGNETOMETER', 3: 'MAV_BOOL', 5: 'PREFLIGHT_CALIBRATION_ACCELEROMETER' },
  MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN: { 1: 'REBOOT_SHUTDOWN_ACTION', 2: 'REBOOT_SHUTDOWN_ACTION', 3: 'REBOOT_SHUTDOWN_ACTION', 6: 'REBOOT_SHUTDOWN_CONDITIONS' },
  MAV_CMD_PREFLIGHT_STORAGE: { 1: 'PREFLIGHT_STORAGE_PARAMETER_ACTION', 2: 'PREFLIGHT_STORAGE_MISSION_ACTION' },
  MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES: { 1: 'MAV_BOOL' },
  MAV_CMD_REQUEST_CAMERA_CAPTURE_STATUS: { 1: 'MAV_BOOL' },
  MAV_CMD_REQUEST_CAMERA_INFORMATION: { 1: 'MAV_BOOL' },
  MAV_CMD_REQUEST_CAMERA_SETTINGS: { 1: 'MAV_BOOL' },
  MAV_CMD_REQUEST_FLIGHT_INFORMATION: { 1: 'MAV_BOOL' },
  MAV_CMD_REQUEST_PROTOCOL_VERSION: { 1: 'MAV_BOOL' },
  MAV_CMD_REQUEST_STORAGE_INFORMATION: { 2: 'MAV_BOOL' },
  MAV_CMD_RESET_CAMERA_SETTINGS: { 1: 'MAV_BOOL' },
  MAV_CMD_SET_CAMERA_FOCUS: { 1: 'SET_FOCUS_TYPE' },
  MAV_CMD_SET_CAMERA_MODE: { 2: 'CAMERA_MODE' },
  MAV_CMD_SET_CAMERA_SOURCE: { 2: 'CAMERA_SOURCE', 3: 'CAMERA_SOURCE' },
  MAV_CMD_SET_CAMERA_ZOOM: { 1: 'CAMERA_ZOOM_TYPE' },
  MAV_CMD_SET_STORAGE_USAGE: { 2: 'STORAGE_USAGE_FLAG' },
  MAV_CMD_START_RX_PAIR: { 1: 'RC_TYPE', 2: 'RC_SUB_TYPE' },
  MAV_CMD_STORAGE_FORMAT: { 2: 'MAV_BOOL', 3: 'MAV_BOOL' },
};

/**
 * @param {string} commandName
 * @param {number} index
 * @returns {string|null}
 */
function paramEnumHint(commandName, index) {
  const byIndex = COMMAND_PARAM_ENUMS[commandName];
  return (byIndex && byIndex[Number(index)]) || null;
}

module.exports = { COMMAND_PARAM_ENUMS, paramEnumHint };
